### ISSUE TITLE
ILP Pay: Payments with no slippage and 1:1 FX rates fail with InsufficientExchangeException

### ISSUE THREAD

**Issue by sappenin** [interledgerjs/interledgerjs#167]
In [IlpPay](https://github.com/interledgerjs/interledgerjs/tree/master/packages/pay), a payment with 0 slippage using a 1:1 FX rate will fail with what seems to be an errant `InsufficientExchangeException`.

This is because the [marginOfError](https://github.com/interledgerjs/interledgerjs/blob/master/packages/pay/src/controllers/amount.ts#L91) will be computed to be 0,  which will fail [this check](https://github.com/interledgerjs/interledgerjs/blob/master/packages/pay/src/controllers/amount.ts#L92) due to not being positive.

Instead, shouldn't [the if-check](https://github.com/interledgerjs/interledgerjs/blob/master/packages/pay/src/controllers/amount.ts#L92) on line 92 only trigger if the marginOfError is negative, like this:

```
if (marginOfError.isNegative()) {  // <-- Only trigger on a negative (0 is valid)
      log.debug(
        'quote failed: probed exchange rate of %s is not greater-than or equal-to minimum of %s',
        lowerBoundRate,
        minExchangeRate
      )
      return PaymentError.InsufficientExchangeRate
    }
```

Here's an example test-case to illustrate the failure (hopefully I'm not misunderstanding the meaning of slippage and marginOfError here).

## Example to Show Failure

```
it('delivers with no slippage and FX rate of 1', async () => {
    const [alice1, alice2] = MirrorPlugin.createPair()
    const [bob1, bob2] = MirrorPlugin.createPair()

    const prices = {
      USD: 1,
      EUR: 1.0805787579827757,
      BTC: 9290.22557286273,
      ETH: 208.46218430418685,
      XRP: 0.2199704769864391,
      JPY: 0.00942729201037,
      GBP: 1.2344993179391268,
    }

    // Override with rate backend for custom rates
    let backend: CustomBackend
    const deps = reduct((Constructor) => Constructor.name === 'RateBackend' && backend)
    backend = new CustomBackend(deps)
    backend.setPrices(prices)

    const app = createApp(
      {
        ilpAddress: 'test.larry',
        spread: 0, // 0% spread
        accounts: {
          alice: {
            relation: 'child',
            plugin: alice2,
            assetCode: 'USD',
            assetScale: 9,
            maxPacketAmount: '899898',
          },
          bob: {
            relation: 'child',
            plugin: bob1,
            assetCode: 'USD',
            assetScale: 9,
          },
        },
      },
      deps
    )
    await app.listen()

    const streamServer = await createServer({
      plugin: bob2,
    })

    const amountToDeliver = Int.from(107643)! 
    const connectionPromise = streamServer.acceptConnection()
    streamServer.on('connection', (connection: Connection) => {
      connection.on('stream', (stream: DataAndMoneyStream) => {
        stream.setReceiveMax(amountToDeliver.toString())
      })
    })

    const {
      sharedSecret,
      destinationAccount: destinationAddress,
    } = streamServer.generateAddressAndSecret()

    const { pay, ...quoteDetails } = await quote({
      amountToDeliver,
      destinationAddress,
      sharedSecret,
      slippage: 0.0,
      plugin: alice1,
      prices,
    })

    const receipt = await pay()

    expect(receipt.error).toBeUndefined()

    const serverConnection = await connectionPromise
    const totalReceived = new BigNumber(serverConnection.totalReceived)
    expect(+totalReceived).toBe(+amountToDeliver)
    expect(+receipt.amountDelivered).toBe(0.00107643)
    expect(+receipt.amountSent).toBeLessThanOrEqual(+quoteDetails.maxSourceAmount)

    await app.shutdown()
    await streamServer.close()
  }, 10000)
```

**Comment by kincaidoneil** [comment]
Hmmmm, the problem is when the probed exchange rate is equal to the minimum exchange rate, the payment may fail: consider if those rates are both `1.0001` and I send a `100` unit packet, `100` will get delivered (intermediary rounds down), but `101` is the minimum destination amount (must be rounded up). You're right that if the probed and minimum rates are both exactly `1`, then I think the payment won't have this issue.

So what do you think about, if the `marginOfError` is `0` and the rate is a positive integer, it should proceed, but if the `marginOrError` is `0` and the rate has any decimal portion then it should fail?

(Side note that the subtraction here is saturating since `Int` and `Ratio`s are always non-negative)

**Comment by sappenin** [comment]
> So what do you think about...

Yeah, great idea!  Also, empirically [in my Java tests](https://github.com/hyperledger/quilt/commit/9f9553f4b41ac7af0c5e9c455c1af383bb1a127a#diff-0eb61dea1d1a94460b42ea8e2321768c2a191d2464b47f7df7b34a037f3c02cfR114) that seems to work.

**Comment by kincaidoneil** [comment]
I think I found a more precise condition, encompassing more cases: rounding errors won't occur if `floor(probedRate) >= ceil(minimumRate)`. If this is true, that means that either: one of the rates is an integer, or the difference between the rates is at least 1, preventing this scenario.

**Comment by sappenin** [comment]
Can you clarify what you think the if-check should be then to cover that case?

**Comment by kincaidoneil** [comment]
I'm proposing exactly this condition. If this condition is true, then I believe one of these two cases is true:
1. Probed rate >= minimum rate _and_ least one of the rates is an integer, OR
2. Probed rate > minimum rate _and_ there exists an integer value between the rates

Some test cases:
- Probed rate is `2` and minimum is `1.9` => `true`
- Probed rate is `2.1` and minimum is `2` => `true`
- Probed rate is `2.1` and minimum is `1.9` => `true`
- Probed rate is `1.5` and minimum is `1.1` => `false` (rounding errors are possible)

Also, if you think about it, this condition literally corresponds to how the rounding error occurs for an individual packet: the minimum destination amount is rounded up and the destination amount is rounded down, and fails if the minimum is greater than the destination amount. So it logically follows that it won't fail if the minimum is less than or equal to the destination amount after this rounding is applied.

**Comment by sappenin** [comment]
Ok, I thought this all made sense, but I think I'm missing something. 

Consider the following example that would have passed using the [original](https://github.com/interledgerjs/interledgerjs/blob/master/packages/pay/src/controllers/amount.ts#L91) logic, but fails with the new logic: An XRP (scale=9):USD(scale=6) FX scenario (with slippage == 2%). In a world where XRP:USD price is `$0.2429546`, then we yield the following:

Probed FX Rate: `0.0002429546`
Min FX Rate: `0.000238095508` (essentially 2% slippage)

Floor(probedRate) == `0`
Ceil(minimumRate) == `1`

Using these numbers and your proposed formula, I get an exception on grounds that "Rounding errors are possible." However, this rate would be fine depending on the number of units in the packet (I think), which begs the question: "Can this calculation be done using _only_ rates, or should we be considering packet amounts and minimums?"

FWIW, here's the current state of the Java implementation: As in JS, there are essentially two checks. First, [checking the rates](https://github.com/hyperledger/quilt/blob/df/ilp-pay/stream-parent/stream-pay/src/main/java/org/interledger/stream/pay/trackers/AmountTracker.java#L300) (JS equivalent forthcoming); and second, [checking the packet-value](https://github.com/hyperledger/quilt/blob/df/ilp-pay/stream-parent/stream-pay/src/main/java/org/interledger/stream/pay/trackers/AmountTracker.java#L326) (JS equivalent [here](https://github.com/interledgerjs/interledgerjs/blob/master/packages/pay/src/controllers/amount.ts#L110)).

**Comment by kincaidoneil** [comment]
Sorry, I was unclear! That condition should still be used in addition to the existing logic [here](https://github.com/interledgerjs/interledgerjs/blob/d6cce52c48fec6bdf95401ee3593360d461aaa93/packages/pay/src/controllers/amount.ts#L91-L117).

Together, it'd be something like this:
1. If `floor(probedRate) >= ceil(minimumRate)`, _skip remaining checks/return success_.
1. Calculate `marginOfError = probedRate - minimumRate`.
1. If `marginOfError <= 0`, return `InsufficientExchangeRate`.
1. Calculate `minPacketAmount = ceil(1 / marginOfError)`.
1. If `maxPacketAmount < minPacketAmount`, return `ExchangeRateRoundingError`.
1. Otherwise, return success.

With this, the example you provided should succeed so long as the max packet amount (in the sender's units) is at least `205,800` nano XRP.

**Comment by sappenin** [comment]
Thanks for your clarifications -- one more case that I'm wondering about. Imagine a scenario where the probed rate is 1.9 and the minRate is also 1.9 (with no slippage).

In this case, `floor(probedRate) >= ceil(minimumRate)` will fail with an `InsufficientExchangeRate`, but in actuality this check should only fail with an `ExchangeRateRoundingError` if the maxPacketAmount amount is less than 10, right?

**Comment by kincaidoneil** [comment]
Hmmmm. I think you're right, but should we solve for this?

It may be useful to solve for the 1:1 case for testing, but I also think it's good to let it fail when the minimum rate is too close to the real rate, like in this case. I think precisely identical rates like this are highly improbable, and we should view setting a reasonable, if small, slippage percentage as a requirement, since that allows "wiggle room" for the payment to complete.

Consider if both rates were 1.33333... (4/3 since they're represented as ratios). In this case, no matter how large the packet amount, it will always fail due to rounding. But to separate this from the `1.9` case, you'd need to identify if the fraction is terminating & the number of decimal places, to determine the minimum packet amount. Also consider that if you're pulling rates from an external API, they often have many decimal places, which means if the rates were exactly equal, the max packet amount would have to be very large to prevent rounding errors.

**Comment by sappenin** [comment]
> Hmmmm. I think you're right, but should we solve for this?

I agree with your logic -- probably best to require some amount of slippage.

One case I was initially concerned about (but no longer am) is a payment path with no FX (i.e., where FX rates == `1.0`). In this case, probed vs actual rates are both `1.0`, and the check will pass.

This is pretty different from the `1.9` or the `4/3` cases, so I feel good about requiring some amount of slippage in the general case.

Thanks for hashing this out with me!
