### ISSUE TITLE
ILP Pay ExchangeRate Calculation: Floor or Ceil?

### ISSUE THREAD

**Issue by sappenin** [interledgerjs/interledgerjs#174]
In [this line of code](https://github.com/interledgerjs/interledgerjs/blob/d6cce52c48fec6bdf95401ee3593360d461aaa93/packages/pay/src/controllers/exchange-rate.ts#L91), the comment seems to indicate that the upper bound exchange rate should be floored because this rate is exclusive. 

However, [the code is using ceil](https://github.com/interledgerjs/interledgerjs/blob/d6cce52c48fec6bdf95401ee3593360d461aaa93/packages/pay/src/controllers/exchange-rate.ts#L94), which would seem to include the upper bound rate (even though it seems like it should be excluded). 

Is this a bug/typo?

@kincaidoneil

**Comment by kincaidoneil** [comment]
Short answer: it's using ceil, _then subtracting one_, which works similarly to flooring but still subtracts one if it converts exactly to an integer (which is what we want since it's exclusive).

Long answer, which I find it best to work through an example:

So, suppose I send `23` units, and `46` are delivered. The lower bound exchange rate is `46 / 23`, which is the lowest the rate could be in order to deliver `46` (inclusive). The upper bound exchange rate is `47 / 23`, since we know that `47` units were not delivered, and therefore it must be lower than this ratio (exclusive). As a decimal, between `2` and `2.0434782609`.

Let's assume the real rate is very close to the upper bound, so `47 / 23 - 0.0000001`, or `2.0434781609`. If the client were to send a packet for `999`, the amount after applying the rate would be `2041.43`, and round down to `2041`. So, `2041` would be the greatest amount that would be delivered by a `999` packet within the rate bounds we know.

So how would the client determine this without knowing the real rate? The client can preform a similar process by using `ceil(999 * (47 / 23))`, but that would incorrectly result in `2042`. With ceil then subtracting 1, the client can correctly determine `2041` as the maximum amount. The reason floor isn't used is if it converted into a destination amount that's an exact integer, since the rate is exclusive, it must be less than that, so you'd need to subtract 1 unit.

**Comment by sappenin** [comment]
Sounds good, thanks for the clarification. Closing this ticket.
